# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:    
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout
      - run:
          name: Run Flutter doctor
          command: flutter doctor
      - run:
          name: Build the Android version
          command: flutter build apk 